#!/bin/env bash

set -e

BZIMAGE=${BZIMAGE:-~/dev/linux/arch/x86_64/boot/bzImage}
INITRAMFS=${INITRAMFS:-~/dev/initramfs/initramfs-busybox-x86.cpio.gz}
ARGS=($@)

help() {
  cat << EOF
Boots up a specified Linux kernel with a barebones busybox userspace

Usage: linux-qemu-boot [-c, --console]

Environment Variables:
    BZIMAGE: Linux image to boot
    INITRAMFS: A cpio'd initramfs for the kernel to boot into
EOF
}

if [[ ${ARGS[0]} == "-h" ]]; then
  help
  exit 0
fi

console=""
if [[ ${ARGS[0]} == "-c" || ${ARGS[0]} == "--console" ]]; then
  console="-nographic -append console=ttyS0"
fi

qemu-system-x86_64   \
  -kernel $BZIMAGE   \
  -initrd $INITRAMFS \
  -enable-kvm        \
  $console
