#!/usr/bin/env bash

set -eu

FILE=${1:-}

if [[ $FILE == "" ]]; then
  echo "Usage: mdp markdown_file"
  exit 1
elif [[ ! -f $FILE ]]; then
  echo "not found: $FILE"
  exit 1
fi

TMPFILE=$(mktemp -u)
pandoc $FILE -o ${TMPFILE}.html
xdg-open ${TMPFILE}.html
